In [134]:
from datascience import *
import numpy as np

## Review of Tables ##

In [135]:
skyscrapers = Table.read_table('../../shared/Data/skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [136]:
skyscrapers.select('name', 'height')

name                              | height
One World Trade Center            | 541.3
Willis Tower                      | 442.14
432 Park Avenue                   | 425.5
Trump International Hotel & Tower | 423.22
Empire State Building             | 381
Bank of America Tower             | 365.8
Stratosphere Tower                | 350.22
Aon Center                        | 346.26
John Hancock Center               | 343.69
WITI TV Tower                     | 329
... (190 rows omitted)

In [137]:
skyscrapers.drop('completed', 'height', 'material')

name                              | city
One World Trade Center            | New York City
Willis Tower                      | Chicago
432 Park Avenue                   | New York City
Trump International Hotel & Tower | Chicago
Empire State Building             | New York City
Bank of America Tower             | New York City
Stratosphere Tower                | Las Vegas
Aon Center                        | Chicago
John Hancock Center               | Chicago
WITI TV Tower                     | Shorewood
... (190 rows omitted)

In [138]:
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [139]:
skyscrapers.where('city', 'Charlotte')

name                             | material       | city      | height | completed
Bank of America Corporate Center | concrete       | Charlotte | 265.48 | 1992
Duke Energy Center               | concrete/steel | Charlotte | 239.7  | 2010
Hearst Tower                     | steel/concrete | Charlotte | 200.81 | 2002

In [140]:
skyscrapers.where('name', 'Empire State Building')

name                  | material | city          | height | completed
Empire State Building | steel    | New York City | 381    | 1931

In [141]:
skyscrapers.where('city', 'New York City').sort('completed')

name                    | material | city          | height | completed
Metropolitan Life Tower | steel    | New York City | 213.36 | 1909
Woolworth Building      | steel    | New York City | 241.4  | 1913
Chanin Building         | steel    | New York City | 197.8  | 1929
Mercantile Building     | steel    | New York City | 192.6  | 1929
Chrysler Building       | steel    | New York City | 318.9  | 1930
The Trump Building      | steel    | New York City | 282.55 | 1930
One Grand Central Place | steel    | New York City | 205.13 | 1930
Empire State Building   | steel    | New York City | 381    | 1931
Twenty Exchange         | steel    | New York City | 225.86 | 1931
500 Fifth Avenue        | steel    | New York City | 212.45 | 1931
... (63 rows omitted)

In [142]:
skyscrapers.where('city', 'New York City').sort('completed', descending=True)

name                                             | material       | city          | height | completed
432 Park Avenue                                  | concrete       | New York City | 425.5  | 2015
Sky                                              | concrete       | New York City | 206    | 2015
One World Trade Center                           | composite      | New York City | 541.3  | 2014
One57                                            | steel/concrete | New York City | 306.07 | 2014
4 World Trade Center                             | composite      | New York City | 297.73 | 2014
Courtyard & Residence Inn Manhattan/Central Park | concrete       | New York City | 229.62 | 2013
Eight Spruce Street                              | concrete       | New York City | 265.18 | 2011
1 MiMA Tower                                     | concrete       | New York City | 194.55 | 2011
Goldman Sachs Headquarters                       | steel          | New York City | 228.3  | 2010
Langham Place                                    | concrete       | New York City | 192.58 | 2010
... (63 rows omitted)

In [143]:
chicago = skyscrapers.where('city', 'Chicago').drop('city')
chicago

name                              | material       | height | completed
Willis Tower                      | steel          | 442.14 | 1974
Trump International Hotel & Tower | concrete       | 423.22 | 2009
Aon Center                        | steel          | 346.26 | 1973
John Hancock Center               | steel          | 343.69 | 1969
The Franklin - North Tower        | composite      | 306.94 | 1989
Two Prudential Plaza              | concrete       | 303.28 | 1990
311 South Wacker Drive            | concrete       | 292.92 | 1990
900 North Michigan Avenue         | concrete/steel | 265    | 1989
Water Tower Place                 | concrete       | 261.88 | 1976
Aqua                              | concrete       | 261.75 | 2009
... (26 rows omitted)

In [144]:
chicago.where('material', 'steel').sort('completed', descending=True)

name                    | material | height | completed
Willis Tower            | steel    | 442.14 | 1974
Aon Center              | steel    | 346.26 | 1973
John Hancock Center     | steel    | 343.69 | 1969
Chase Tower             | steel    | 259.08 | 1969
Richard J. Daley Center | steel    | 197.51 | 1965

## Numbers ##

In [145]:
4 * 5

20

In [146]:
20/3

6.666666666666667

In [147]:
20/2

10.0

In [148]:
1234 **5

2861381721051424

In [149]:
1234 ** 1234

48184467781382543701667186039468406661059770237590274727670474872867568934066212120125133953550629961484891523453397766904292741725027019645437267985042784717562212455213265145073576158446772320656790521515384533153285495122560467130551068937365382642309092956110550380937116582823950116105467284919886128590021120491211422848352480419801389040432671756358444906225483817656922238136306002774235317628882806945193646888148396110892049431698226720231373322565553173892155104287328274243305595665720786784052656812367125148945799485499060066329553808509237311004983159894774937428752149540862686417306258598574741354798734543908917749037010338607293558391168741173229347205324015819180886782731783732875096308025479318621477536729557178851277749719374746640105570680704597488214460168162719035143192317718562628271959732323123847141889566569180545843169342410738692059982444746465750802950208574020617939255322870389259522352007286309084437654560750826135123276437360339867137662914521505757477954199067061537563338324827971696801982963501680500285473348151566773437596060788388816834765832275133438433921225741018069257650081651893412763515411183995641907421720698187041665296617342826301233824768831086783439617690340317902242011073693697825044232174730876417203502412742085342749470261962000902738749779130464597185957223365845266728739264096596554562810900489160285087089151363421121896616575007056439552166409310603897415780357105218172824045265515881762471530724320743935876223471758489130857861949736325801719247163392163145092104862730777665632878101469684676983177748845758819134783307275384116307332565581471205450219638137864387568253396048525319846029722597087368081615296780675739066314774724547006391416740049175425483980982557830287877118477623151223431159832554386188341940675670910313367805899112248803570997473057794418174867654496284922646065073429519234590181376956226715629044946363751414558194273837719521633486883608951520130473135848525228767697904589545099613408858934772678955107374792767376297292404355699412788887158297703071562694349633862471115563026643188726923335031942038276485070702440112289573556176109970627523424440589934713944485023114357294128614721641112627517540349238220184422744440362721622786094864017694819354467741507712876404983391152695521440373975295468154208059821687654408426427370963930322531227395895396783921477437273314199002421808939747302217153865116186806351980760710239964563379901328372415061933640351961853616394184876278706277214297206989695471340253866298118966493903627998818702216683968716037963198654625001668768390791943686432733286824675468274040171973201059002888713965690564527215419345100503188258777506372065686193271207542007415422109631813074486204833751677472525228744950194297089998305021078379670692156515896561318156670094486647187285361909788624195866103332184213842805429511053631902833667630273693526699848894312061513323511126288640008264849029913769883352116160378319937025276742846457501369721989078408607355941517261584972558483819760496804231338012065441081939772196754109683768808242484290927174759258520839532703010720373548957783991479615682174614219692539567777715560109326389875468292301222743028820913581258063284673412787274389056140124677069653486630962880192937633527058165237839406307326482619493415666561288774929091975803346338652727476500670928651812154306332363280019281880148780695662032811060669099701522746512853264775139655489705043573689252437465482977809592752059272522878781208311791893662451561020284928906469358115442883064671084339186725298116883304622860824362268174217031187839248915211550033719913619980315078125050194505282396757349145204835262063407488072671571413182055277457862261818131387963934879102237121895980689553963436483304289698371277085427432858554859126640569432899045006806292448711540736

In [150]:
4 / 700

0.005714285714285714

In [151]:
4 / 70000000000000000000000000

5.714285714285715e-26

In [152]:
0.12345678901234567890123456789

0.12345678901234568

In [153]:
0.12345678901234567890123456789 - 0.1234567890123456789

0.0

In [154]:
10 ** 0.5

3.1622776601683795

In [155]:
16 ** 0.5

4.0

In [156]:
(10 ** 0.5) **2

10.000000000000002

In [157]:
(16 ** 0.5) **2

16.0

## Strings ##

In [158]:
'I am tired'

'I am tired'

In [159]:
"I'm tired"

"I'm tired"

In [160]:
"I'm tired"

"I'm tired"

In [161]:
'water' + 'melon'

'watermelon'

In [162]:
'water' + ' ' + 'melon'

'water melon'

In [163]:
'ha' *10

'hahahahahahahahahaha'

In [164]:
'lo'*5

'lololololo'

In [165]:
int('3')

3

In [166]:
int(float('3.0'))

3

In [167]:
float('3.0')

3.0

In [168]:
str(3)

'3'

In [169]:
str(4.5)

'4.5'

## Types ##

In [170]:
type(3)

int

In [171]:
a = 10
type(a)

int

In [172]:
type(4.5)

float

In [173]:
type('abc')

str

In [174]:
type(skyscrapers)

datascience.tables.Table

In [175]:
type(True)

bool

In [176]:
type(abs)

builtin_function_or_method

## Arrays ##

In [177]:
my_array = make_array(1, 2, 3, 4)
my_array

array([1, 2, 3, 4])

In [178]:
my_array * 2

array([2, 4, 6, 8])

In [179]:
my_array **2

array([ 1,  4,  9, 16])

In [180]:
my_array + 1

array([2, 3, 4, 5])

In [181]:
my_array

array([1, 2, 3, 4])

In [182]:
len(my_array)

4

In [183]:
sum(my_array)

10

In [184]:
sum(my_array) / len(my_array)

2.5

In [185]:
np.average(my_array)

2.5

In [186]:
another = make_array(60, 70, 80, 90)
another

array([60, 70, 80, 90])

In [187]:
my_array + another

array([61, 72, 83, 94])

In [188]:
yet_another = make_array(5, 6, 7)
yet_another

array([5, 6, 7])

In [189]:
my_array[:3] + yet_another

array([ 6,  8, 10])

In [190]:
my_array / 4

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [191]:
make_array('a', 'b', 'c')

array(['a', 'b', 'c'],
      dtype='<U1')

## Columns of Tables are Arrays ##

In [192]:
Arrests_Carrboro = Table.read_table('../../shared/Data/Police_Arrests_Made.csv').where('City', 'CARRBORO')

Arrests_Carrboro

X        | Y       | Incident_Id | Primary_Charge                               | Street                               | City     | State | Zipcode | Date_of_Arrest         | Age  | Race | Gender | Ethnicity | Type_of_Arrest                  | Drugs_or_Alcohol_Present | Weapon_Present | Disposition             | latitude | longitude | ObjectId
-79.0681 | 35.9107 | 26150       | LARCENY-CREDIT CARD                          | 302 EAST MAIN STREET                 | CARRBORO | NC    | 27517   | 2011/01/27 05:25:00+00 | 33   | B    | M      | nan       | TAKEN INTO CUSTODY (WARRANT/LP) | N                        | UNARMED        | CLEARED BY ARREST       | 35.9107  | -79.0681  | 1010
-79.0672 | 35.9089 | 24635       | OPEN CONTAINER                               | BREWER LN / GUTHERIE                 | CARRBORO | NC    | 27516   | 2010/05/02 02:34:00+00 | 25   | W    | M      | N         | SUMMONED/CITED                  | Y                        | UNARMED        | ARREST/NO INVESTIGATION | 35.9089  | -79.0672  | 6321
-79.0672 | 35.9089 | 24636       | OPEN CONTAINER                               | BREWER LN/ GUTHERIE                  | CARRBORO | NC    | 27516   | 2010/05/02 02:49:00+00 | 24   | W    | M      | N         | SUMMONED/CITED                  | Y                        | UNARMED        | ARREST/NO INVESTIGATION | 35.9089  | -79.0672  | 6322
-79.074  | 35.9002 | 27205       | POSSESSION MARIJUANA                         | SMITH LEVEL RD/CARRBORO PUBLIC WORKS | CARRBORO | NC    | 27516   | 2011/08/13 14:20:00+00 | nan  | nan  | nan    | nan       | SUMMONED/CITED                  | N                        | UNARMED        | CLEARED BY ARREST       | 35.9002  | -79.074   | 6323
-79.0724 | 35.9302 | 27915       | IMPAIRED DRIVING DWI                         | SEWELL SCHOOL RD NEAR HANOVER PLACE  | CARRBORO | NC    | 27516   | 2012/01/01 03:17:00+00 | 21   | A    | M      | N         | ON VIEW                         | Y                        | UNARMED        | CLEARED BY ARREST       | 35.9302  | -79.0724  | 6324
-79.0662 | 35.9099 | 29461       | B&E-VEHICLE                                  | 412 EAST MAIN ST                     | CARRBORO | NC    | 27516   | 2012/11/22 23:36:00+00 | 40   | B    | M      | N         | ON VIEW                         | Y                        | UNARMED        | CLEARED BY ARREST       | 35.9099  | -79.0662  | 6801
-79.0709 | 35.9218 | 33581       | DOMESTIC VIOLENCE  BAIL AND PRETRAIL RELEASE | 306 ESTES EXT                        | CARRBORO | NC    | 27516   | 2015/04/10 01:56:00+00 | 36   | A    | M      | nan       | TAKEN INTO CUSTODY (WARRANT/LP) | N                        | UNARMED        | CLEARED BY ARREST       | 35.9218  | -79.0709  | 6802
-79.0658 | 35.911  | 35101       | FAIL TO APPEAR/COMPL                         | W ROSEMARY ST/N MERRITT MILL         | CARRBORO | NC    | 27516   | 2016/02/02 00:42:00+00 | 23   | B    | M      | N         | TAKEN INTO CUSTODY (WARRANT/LP) | U                        | UNARMED        | CLEARED BY ARREST       | 35.911   | -79.0658  | 6803
-79.0662 | 35.9116 | 35381       | SIMPLE ASSAULT                               | 200 SUNSET DR                        | CARRBORO | NC    | 27516   | 2016/03/24 16:19:00+00 | 45   | B    | M      | N         | TAKEN INTO CUSTODY (WARRANT/LP) | N                        | UNARMED        | CLEARED BY ARREST       | 35.9116  | -79.0662  | 6804
-79.0851 | 35.9004 | 35747       | PANHANDLING/LOITERING                        | 310 WESTBROOK DR                     | CARRBORO | NC    | 27516   | 2016/06/05 04:15:00+00 | 51   | B    | M      | N         | SUMMONED/CITED                  | Y                        | UNARMED        | CLEARED BY ARREST       | 35.9004  | -79.0851  | 6805
... (137 rows omitted)

In [193]:
Arrests_Carrboro.select('Age')

Age
33
25
24
nan
21
40
36
23
45
51
... (137 rows omitted)

In [194]:
np.average(Arrests_Carrboro.column('Age'))

nan

In [195]:
type(Arrests_Carrboro.select('Age'))

datascience.tables.Table

In [196]:
Arrests_Carrboro.column('Age')

array([ 33.,  25.,  24.,  nan,  21.,  40.,  36.,  23.,  45.,  51.,  31.,
        40.,  28.,  26.,  nan,  39.,  34.,  25.,  26.,  25.,  50.,  19.,
        41.,  35.,  29.,  22.,  42.,  19.,  32.,  nan,  18.,  18.,  23.,
        52.,  47.,  24.,  24.,  23.,  48.,  18.,  28.,  22.,  33.,  34.,
        60.,  30.,  35.,  23.,  55.,  22.,  19.,  20.,  19.,  nan,  28.,
        51.,  21.,  50.,  nan,  21.,  31.,  41.,  21.,  45.,  24.,  25.,
        20.,  23.,  24.,  20.,  41.,  24.,  26.,  21.,  20.,  38.,  48.,
        49.,  42.,  49.,  44.,  24.,  nan,  30.,  36.,  25.,  46.,  56.,
        66.,  20.,  36.,  42.,  44.,  49.,  26.,  20.,  61.,  26.,  38.,
        35.,  45.,  49.,  30.,  33.,  34.,  51.,  52.,  37.,  18.,  22.,
        32.,  28.,  31.,  18.,  40.,  27.,  47.,  19.,  44.,  23.,  26.,
        24.,  26.,  27.,  23.,  18.,  19.,  nan,  48.,  32.,  20.,  21.,
        27.,  25.,  47.,  22.,  23.,  21.,  26.,  22.,  20.,  25.,  38.,
        49.,  46.,  43.,  24.])

In [197]:
type(Arrests_Carrboro.column('Age'))

numpy.ndarray

In [198]:
len(Arrests_Carrboro.column('Age'))

147

In [199]:
len(Arrests_Carrboro.column('Age'))

147

In [200]:
np.average(Arrests_Carrboro.column('Age'))

nan

In [201]:
np.mean(Arrests_Carrboro.column('Age'))

nan

In [202]:
np.nanmean(Arrests_Carrboro.column('Age'))

32.178571428571431

In [203]:
CH_OP = Table.read_table('../../shared/Data/Police_Arrests_Made.csv').where(
    'City', 'CHAPEL HILL').where(
    'Primary_Charge', 'OPEN CONTAINER')
CH_OP

X        | Y       | Incident_Id | Primary_Charge | Street                             | City        | State | Zipcode | Date_of_Arrest         | Age  | Race | Gender | Ethnicity | Type_of_Arrest | Drugs_or_Alcohol_Present | Weapon_Present | Disposition       | latitude | longitude | ObjectId
-79.0531 | 35.9147 | 26290       | OPEN CONTAINER | 108 HENDERSON ST                   | CHAPEL HILL | nan   | 27614   | 2011/02/18 01:30:00+00 | nan  | nan  | nan    | nan       | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.9147  | -79.0531  | 248
-79.056  | 35.9131 | 24539       | OPEN CONTAINER | 100 BLOCK WEST FRANKLIN STREET     | CHAPEL HILL | NC    | 27517   | 2010/04/15 23:33:00+00 | 45   | B    | M      | N         | ON VIEW        | Y                        | UNARMED        | CLEARED BY ARREST | 35.9131  | -79.056   | 294
-79.0225 | 35.9356 | 32904       | OPEN CONTAINER | 104 EPHESUS CHURCH RD              | CHAPEL HILL | NC    | 27517   | 2014/11/09 16:09:00+00 | 39   | A    | M      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.9356  | -79.0225  | 313
-79.0219 | 35.9339 | 26602       | OPEN CONTAINER | 1250 EPHESUS CHURCH RD             | CHAPEL HILL | NC    | 27517   | 2011/04/17 00:15:00+00 | 52   | W    | M      | H         | ON VIEW        | Y                        | UNARMED        | CLEARED BY ARREST | 35.9339  | -79.0219  | 408
-79.0559 | 35.9032 | 25508       | OPEN CONTAINER | N COLUMBIA ST                      | CHAPEL HILL | NC    | 27517   | 2010/09/18 13:07:00+00 | 24   | B    | M      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.9032  | -79.0559  | 562
-79.0559 | 35.9032 | 25509       | OPEN CONTAINER | N COLUMBIA ST                      | CHAPEL HILL | NC    | 27517   | 2010/09/18 13:01:00+00 | 21   | W    | F      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.9032  | -79.0559  | 563
-79.0579 | 35.9204 | 32425       | OPEN CONTAINER | E LONGVIEW ST                      | CHAPEL HILL | NC    | 27517   | 2014/08/22 23:20:00+00 | 24   | W    | M      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.9204  | -79.0579  | 713
-79.0578 | 35.907  | 32434       | OPEN CONTAINER | RANSOM ST // MCCAULEY ST           | CHAPEL HILL | NC    | 27517   | 2014/08/23 00:10:00+00 | 26   | W    | M      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.907   | -79.0578  | 715
-79.042  | 35.8789 | 32452       | OPEN CONTAINER | N COLUMBIA ST // PRITCHARD AVE EXT | CHAPEL HILL | NC    | 27517   | 2014/08/23 23:50:00+00 | 21   | W    | F      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.8789  | -79.042   | 722
-79.0611 | 35.9174 | 24637       | OPEN CONTAINER | 131 CALDWELL ST/CHURCH ST          | CHAPEL HILL | NC    | 27516   | 2010/05/02 02:56:00+00 | 22   | W    | M      | N         | SUMMONED/CITED | Y                        | UNARMED        | CLEARED BY ARREST | 35.9174  | -79.0611  | 1006
... (1259 rows omitted)

In [204]:
# what is the average age of open container arrests in Chapel Hill

np.nanmean(CH_OP.column('Age'))

42.224603174603175

In [205]:
# Do the same for Carrboro

In [206]:
np.nanmean(Arrests_Carrboro.where('Primary_Charge', 'OPEN CONTAINER').column('Age'))

34.75

In [207]:
len(CH_OP.column('Age'))

1269

In [208]:
len(Arrests_Carrboro.where('Primary_Charge', 'OPEN CONTAINER').column('Age'))

4